### ISSUE TITLE
demo executed fail

### ISSUE THREAD

**Issue by lonsathing** [yinyunie/RfDNet#10]
Begin to finetune from the existing weight.
Loading checkpoint from out/pretrained_models/pretrained_weight.pth.
set() subnet missed.
Weights for finetuning loaded.
Loading data.
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    demo.run(cfg)
  File "/home/**/code/RfDNet-main/demo.py", line 409, in run
    our_data = generate(cfg, net.module, input_data, post_processing=False)
  File "/home/**/code/RfDNet-main/demo.py", line 223, in generate
    eval_dict, parsed_predictions = parse_predictions(end_points, data, cfg.eval_config)
  File "/home/**/code/RfDNet-main/net_utils/ap_helper.py", line 257, in parse_predictions
    assert (len(pick) > 0)
AssertionError

**Comment by yinyunie** [comment]
did you use the same input, weight as in the demo?

**Comment by lonsathing** [comment]
thank you，I had implemented it success,the result is impressive
