### ISSUE TITLE
Missing file external.pointnet2.pytorch_utils

### ISSUE THREAD

**Issue by CurryYuan** [yinyunie/RfDNet#3]
When I run command `python main.py --config configs/config_files/ISCNet_detection.yaml --mode train`, I met the following error.

```
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    import train
  File "/home/Projects/RfDNet/train.py", line 4, in <module>
    from models.optimizers import load_optimizer, load_scheduler, load_bnm_scheduler
  File "/home/Projects/RfDNet/models/optimizers.py", line 5, in <module>
    from external.pointnet2.pytorch_utils import BNMomentumScheduler
ModuleNotFoundError: No module named 'external.pointnet2'
```

**Comment by yinyunie** [comment]
Hi, I fixed this bug. Could you try again? Please let me know if there are
further bugs.

Best regards,
Yinyu

**Comment by CurryYuan** [comment]
Thanks, the bug is fixed.
